source 'https://github.com/noughts/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NNCrossFadeImageView_Example', :exclusive => true do
  pod "NNCrossFadeImageView", :path => "../"
  pod "NBULog"
end

target 'NNCrossFadeImageView_Tests', :exclusive => true do
  pod "NNCrossFadeImageView", :path => "../"

  
end
